/**:
  ros__parameters:
    # weight files
    trt_precision: fp16
    cloud_capacity: 1000000
    post_process_params:
      # post-process params
      circle_nms_dist_threshold: 0.5
      iou_nms_search_distance_2d: 10.0
      iou_nms_threshold: 0.1
      yaw_norm_thresholds: [0.3, 0.3, 0.3, 0.3, 0.0]
      # CAR, TRUCK, BUS, BICYCLE, PEDESTRIAN
      score_thresholds: [0.35, 0.35, 0.35, 0.35, 0.35]
    densification_params:
      world_frame_id: map
      num_past_frames: 1
