/**:
  ros__parameters:

    enable_read_all_target_ids: true
    target_ids: [
                 "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                 "11", "12", "13", "14", "15", "16", "17", "18", "19"
                ]
    queue_size_for_output_pose: 10 # Queue size for output/pose_with_covariance publisher

    # marker name
    marker_name: "reflector"

    # for marker detection algorithm
    resolution: 0.05
    # A sequence of high/low intensity to perform pattern matching.
    # 1: high intensity (positive match), 0: not consider, -1: low intensity (negative match)
    intensity_pattern: [-1, -1, 0, 1, 1, 1, 1, 1, 0, -1, -1]
    match_intensity_difference_threshold: 20
    positive_match_num_threshold: 3
    negative_match_num_threshold: 3
    vote_threshold_for_detect_marker: 20
    marker_to_vehicle_offset_y: -2.3
    marker_height_from_ground: 1.075
    lower_ring_id_init: 128
    upper_ring_id_init: 0
    reference_ring_number: 255 # set to 255 to disable ring filtering

    # for interpolate algorithm
    self_pose_timeout_sec: 1.0
    self_pose_distance_tolerance_m: 1.0

    # for validation
    limit_distance_from_self_pose_to_nearest_marker: 2.0
    limit_distance_from_self_pose_to_nearest_marker_y: 1.0
    limit_distance_from_self_pose_to_marker: 2.0

    # base_covariance
    # [TBD] This value is dynamically scaled according to the distance at which markers are detected.
    base_covariance: [0.04, 0.0,  0.0,  0.0,        0.0,        0.0,
                      0.0,  0.04, 0.0,  0.0,        0.0,        0.0,
                      0.0,  0.0,  0.01, 0.0,        0.0,        0.0,
                      0.0,  0.0,  0.0,  0.00007569, 0.0,        0.0,
                      0.0,  0.0,  0.0,  0.0,        0.00007569, 0.0,
                      0.0,  0.0,  0.0,  0.0,        0.0,        0.00030625]

    # for visualize the detected marker pointcloud
    marker_width: 0.8

    # for save log
    enable_save_log: false
    save_file_directory_path: detected_reflector_intensity_front_lower_right
    save_file_name: detected_reflector_intensity
    save_frame_id: pandar_40p_front
    radius_for_extracting_marker_pointcloud: 0.4 # [m] within
    queue_size_for_debug_pub_msg: 10 # Queue size for debug publishers
