/**:
  ros__parameters:
    approximate_sync: false
    precision: fp16
    mean: [123.675, 116.28, 103.53] # It depends on the data on which ML model is trained
    std: [58.395, 57.12, 57.375] # It depends on the data on which ML model is trained
    over_exposure_threshold: 0.85
    under_exposure_threshold: -0.85
    classifier_type: 1
    traffic_light_type: 0
