/**:
  ros__parameters:
    min_x: -100.0
    max_x: 150.0
    min_y: -70.0
    max_y: 70.0
    margin_max_z: 0.0  # to extend the crop box max_z from vehicle_height
    margin_min_z: -2.5 # to extend the crop box min_z from ground
    negative: False
    processing_time_threshold_sec: 0.01
