/**:
  ros__parameters:
    fusion_distance: 100.0
    strict_iou_fusion_distance: 100.0
    strict_iou_match_mode: "iou"
    rough_iou_match_mode: "iou_x"
    use_cluster_semantic_type: false
    only_allow_inside_cluster: true
    roi_scale_factor: 1.1
    iou_threshold:
      UNKNOWN : 0.1
      CAR : 0.65
      TRUCK : 0.65
      BUS : 0.65
      TRAILER : 0.65
      MOTORCYCLE : 0.65
      BICYCLE : 0.65
      PEDESTRIAN : 0.65
    remove_unknown: false
