/**:
  ros__parameters:
    obstacle_slow_down:
      slow_down_planning:
        slow_down_min_acc: -1.0         # slow down min deceleration [m/ss]
        slow_down_min_jerk: -1.0        # slow down min jerk [m/sss]

        lpf_gain_slow_down_vel: 0.0 # low-pass filter gain for slow down velocity
        lpf_gain_lateral_distance: 0.8 # low-pass filter gain for lateral distance from obstacle to ego's path
        lpf_gain_dist_to_slow_down: 0.8 # low-pass filter gain for distance to slow down start

        time_margin_on_target_velocity: 1.5 # [s]

        # parameters to calculate slow down velocity by linear interpolation
        object_type_specified_params:
          default:  # values used if not specified for some object type
            left:
              moving:
                min_lat_margin: 0.2
                max_lat_margin: 1.0
                min_ego_velocity: 2.0
                max_ego_velocity: 8.0
              static:
                min_lat_margin: 0.2
                max_lat_margin: 1.0
                min_ego_velocity: 4.0
                max_ego_velocity: 8.0
            right:
              moving:
                min_lat_margin: 0.2
                max_lat_margin: 1.0
                min_ego_velocity: 2.0
                max_ego_velocity: 8.0
              static:
                min_lat_margin: 0.2
                max_lat_margin: 1.0
                min_ego_velocity: 4.0
                max_ego_velocity: 8.0
            wheel_off_track_scale: 0.0 # scale factor for additional stop margin against ego's wheel off-track. Even if this value is set to 0.0, the planner considers the nominal wheel off-track.
          # car.left.moving.min_ego_velocity: 3.0  # example specific override

        moving_object_speed_threshold: 0.5 # [m/s] how fast the object needs to move to be considered as "moving"
        moving_object_hysteresis_range: 0.1 # [m/s] hysteresis range used to prevent chattering when obstacle moves close to moving_object_speed_threshold

      obstacle_filtering:
        object_type:
          unknown: false
          car: true
          truck: true
          bus: true
          trailer: true
          motorcycle: true
          bicycle: true
          pedestrian: true
          pointcloud: false

        # Previously and ideally, the min_lat_margin was 0.
        # However, the objects whose lateral margin is between 0 and 'wheel_off_track_scale times wheel_off_track' are ignored by the obstacle_slow_down module unexpectedly due to the current implementation.
        # Therefore, we set the min_lat_margin to a large negative value temporarily.
        min_lat_margin: -10.0  # lateral margin between obstacle and trajectory band with ego's width to avoid the conflict with the obstacle_stop
        max_lat_margin: 1.1  # lateral margin between obstacle and trajectory band with ego's width
        lat_hysteresis_margin: 0.2
        max_lat_velocity: 3.0 # [m/s] max lateral velocity of obstacle to be considered

        successive_num_to_entry_slow_down_condition: 5
        successive_num_to_exit_slow_down_condition: 5
