# Description:
#   required_diags:
#     <name>: {is_active: <is_active>, status: <status>}
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # localization
      ## /localization/001-topic_status/initialpose
      "topic_state_monitor_initialpose3d: localization_topic_status": default

      ## /localization/001-topic_status/pose_twist_fusion_filter
      "topic_state_monitor_pose_twist_fusion_filter_pose: localization_topic_status": default

      ## /localization/002-tf
      "topic_state_monitor_transform_map_to_base_link: localization_topic_status": default

      ## /localization/003-matching_score
      "ndt_scan_matcher: scan_matching_status": default

      ## /localization/004-accuracy
      "localization_error_monitor: ellipse_error_status": default

      # map
      ## /map/001-topic_status/pointcloud_map
      "topic_state_monitor_pointcloud_map: map_topic_status": default

      # perception
      ## /perception/001-topic_status/traffic_signals
      "topic_state_monitor_traffic_light_recognition_traffic_signals: perception_topic_status": default

      ## /perception/001-topic_status/objects
      "topic_state_monitor_object_recognition_objects: perception_topic_status": default

      ## /perception/001-topic_status/pointcloud
      "topic_state_monitor_obstacle_segmentation_pointcloud: perception_topic_status": default

      ## /perception/002-detection_delay
      "multi_object_tracker: Tracker Timing Diagnostics": default
