units:
  - path: /localization/autonomous_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }
      - { type: link, link: /localization/pull_over }
      - { type: link, link: /localization/comfortable_stop }

  - path: /localization/pull_over_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }
      - { type: link, link: /localization/comfortable_stop }

  - path: /localization/comfortable_stop_available
    type: and
    list:
      - { type: link, link: /localization/emergency_stop }

  # *******************************************************************************
  # NOTE: Please modify this section according to your environment and requirements.
  # *******************************************************************************
  - path: /localization/emergency_stop
    type: and
    list:
      - { type: link, link: /localization/001-topic_status/initialpose-error }
      - { type: link, link: /localization/001-topic_status/pose_twist_fusion_filter-error }
      - { type: link, link: /localization/002-tf-error }
      - { type: link, link: /localization/003-matching_score-error }
      - { type: link, link: /localization/004-accuracy-error }

  - path: /localization/comfortable_stop
    type: and

  - path: /localization/pull_over
    type: and

  - path: /localization/none
    type: and

  - path: /localization/001-topic_status/initialpose-error
    type: warn-to-ok
    item:
      type: link
      link: /localization/001-topic_status/initialpose

  - path: /localization/001-topic_status/pose_twist_fusion_filter-error
    type: warn-to-ok
    item:
      type: link
      link: /localization/001-topic_status/pose_twist_fusion_filter

  - path: /localization/002-tf-error
    type: warn-to-ok
    item:
      type: link
      link: /localization/002-tf

  - path: /localization/003-matching_score-error
    type: warn-to-ok
    item:
      type: link
      link: /localization/003-matching_score

  - path: /localization/004-accuracy-error
    type: warn-to-ok
    item:
      type: link
      link: /localization/004-accuracy

  - path: /localization/001-topic_status/initialpose
    type: diag
    node: topic_state_monitor_initialpose3d
    name: localization_topic_status
    timeout: 1.0

  - path: /localization/001-topic_status/pose_twist_fusion_filter
    type: diag
    node: topic_state_monitor_pose_twist_fusion_filter_pose
    name: localization_topic_status
    timeout: 1.0

  - path: /localization/002-tf
    type: diag
    node: topic_state_monitor_transform_map_to_base_link
    name: localization_topic_status
    timeout: 1.0

  - path: /localization/003-matching_score
    type: diag
    node: ndt_scan_matcher
    name: scan_matching_status
    timeout: 1.0

  - path: /localization/004-accuracy
    type: diag
    node: localization
    name: localization_error_monitor
    timeout: 1.0
