/**:
  ros__parameters:
    input_channels:
      # Merged detected objects, i.e. "/perception/object_recognition/detection/objects"
      detected_objects:
        optional:
          name: "detected_objects"
          short_name: "all"
      # LIDAR - rule-based
      lidar_clustering:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: false
          can_trust_extension: false
          can_trust_classification: false
          can_trust_orientation: false
        optional:
          name: "clustering"
          short_name: "Lcl"
      # LIDAR - DNN
      lidar_centerpoint:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: true
          can_trust_extension: true
          can_trust_classification: true
          can_trust_orientation: true
        optional:
          name: "centerpoint"
          short_name: "Lcp"
      lidar_centerpoint_short_range:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: true
          can_trust_extension: true
          can_trust_classification: true
          can_trust_orientation: true
        optional:
          name: "centerpoint_short_range"
          short_name: "LcpS"
      lidar_apollo:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: true
          can_trust_extension: true
          can_trust_classification: true
          can_trust_orientation: true
        optional:
          name: "apollo"
          short_name: "Lap"
      # LIDAR-CAMERA - DNN
      # cspell:ignore lidar_pointpainting pointpainting
      lidar_pointpainting:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: true
          can_trust_extension: true
          can_trust_classification: true
          can_trust_orientation: true
        optional:
          name: "pointpainting"
          short_name: "Lpp"
      # CAMERA-LIDAR
      camera_lidar_fusion:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: false
          can_trust_extension: false
          can_trust_classification: true
          can_trust_orientation: false
        optional:
          name: "camera_lidar_fusion"
          short_name: "CLf"
      # CAMERA-LIDAR-IRREGULAR
      camera_lidar_fusion_irregular:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: false
          can_trust_extension: false
          can_trust_classification: true
          can_trust_orientation: false
        optional:
          name: "camera_lidar_fusion_irregular"
          short_name: "Irreg"
      # CAMERA-LIDAR+TRACKER
      detection_by_tracker:
        flags:
          can_spawn_new_tracker: false
          can_trust_existence_probability: false
          can_trust_extension: false
          can_trust_classification: false
          can_trust_orientation: false
        optional:
          name: "detection_by_tracker"
          short_name: "dbT"
      # RADAR
      radar:
        flags:
          can_spawn_new_tracker: true
          can_trust_existence_probability: true
          can_trust_extension: false
          can_trust_classification: true
          can_trust_orientation: false
        optional:
          name: "radar"
          short_name: "Rad"
