/**:
  ros__parameters:
    # default tracker models for each class
    car_tracker: "multi_vehicle_tracker"
    truck_tracker: "multi_vehicle_tracker"
    bus_tracker: "multi_vehicle_tracker"
    trailer_tracker: "multi_vehicle_tracker"
    pedestrian_tracker: "pedestrian_and_bicycle_tracker"
    bicycle_tracker: "pedestrian_and_bicycle_tracker"
    motorcycle_tracker: "pedestrian_and_bicycle_tracker"

    # default tracker node parameters
    publish_rate: 10.0
    world_frame_id: map
    ego_frame_id: base_link
    enable_delay_compensation: true
    consider_odometry_uncertainty: false
    enable_unknown_object_velocity_estimation: true
    enable_unknown_object_motion_output: false

    # tracker parameters
    tracker_lifetime: 1.0  # [s]
    min_known_object_removal_iou: 0.1  # [ratio]
    min_unknown_object_removal_iou: 0.001  # [ratio]

    # pruning parameters
    # list of generalized IoU thresholds for each class
    pruning_generalized_iou_thresholds:
      # UNKNOWN,  CAR, TRUCK,  BUS, TRAILER, MOTORCYCLE, BICYCLE, PEDESTRIAN
      [    -0.3, -0.4,  -0.6, -0.6,    -0.6,       -0.1,    -0.1,       -0.1]
    pruning_distance_thresholds:
      # UNKNOWN, CAR, TRUCK, BUS, TRAILER, MOTORCYCLE, BICYCLE, PEDESTRIAN
      [     9.0, 5.0,   9.0, 9.0,     9.0,        4.0,     3.0,        2.0]

    # debug parameters
    publish_processing_time: true
    publish_processing_time_detail: false
    publish_tentative_objects: false
    publish_debug_markers: false
    diagnostics_warn_delay: 0.5      # [sec]
    diagnostics_error_delay: 1.0     # [sec]
    diagnostics_warn_extrapolation: 0.5      # [sec]
    diagnostics_error_extrapolation: 1.0      # [sec]
