/**:
  ros__parameters:
    debug_mode: false
    rosbag_length: 10.0
    maximum_queue_size: 5
    timeout_sec: 0.01
    is_motion_compensated: false
    publish_synchronized_pointcloud: true
    keep_input_frame_in_synchronized_pointcloud: true
    publish_previous_but_late_pointcloud: false
    synchronized_pointcloud_postfix: pointcloud
    input_twist_topic_type: twist
    input_topics: [
                    "/sensing/lidar/right/pointcloud_before_sync", # Fill this after using the right point cloud
                    "/sensing/lidar/top/pointcloud_before_sync", # 0.05
                    "/sensing/lidar/left/pointcloud_before_sync", # Fill this after using the left point cloud
                ]
    output_frame: base_link
    matching_strategy:
          type: advanced
          lidar_timestamp_offsets: [0.0, 0.0, 0.0]
          lidar_timestamp_noise_window: [0.02, 0.02, 0.02]
