# Description:
#   required_diags:
#     <name>: {is_active: <is_active>, status: <status>}
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      
      # control
      joy_controller_connection: default

      # locallization
      localization_accuracy: default
      ndt_scan_matcher: default

      # system
      bagpacker: default
      NTP Offset: default
      CPU Temperature: default
      CPU Usage: default
      CPU Thermal Throttling: default
      CPU Frequency: default
      CPU Load Average: default
      GPU Temperature: default
      GPU Usage: default
      GPU Memory Usage: default
      GPU Thermal Throttling: default
      Memory Usage: default
      Network Usage: default
      Network Traffic: default
      HDD Temperature: default
      HDD Usage: default
      HDD PowerOnHours: default
      HDD TotalDataWritten: default
      High-load: default
      High-mem: default
      Tasks Summary: default

      #vehicle
      vehicle_errors: default
