/**:
  ros__parameters:
    range_calc_frame_id: "base_link"
    range_calc_offset:
      x: 0.0 # [m]
      y: 0.0 # [m]

    range_thresholding_mode: "distance" # [distance, area]

    sort_target:
      UNKNOWN:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      CAR:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      TRUCK:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      BUS:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      TRAILER:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      MOTORCYCLE:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      BICYCLE:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
         # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]

      PEDESTRIAN:
        publish: true
        min_velocity_threshold: 5.5 # [m/s]
        range_threshold:
          # when range_thresholding_mode = distance
          max_distance: 1000.0 # [m]
          min_distance: 80.0 # [m]
          # when range_thresholding_mode = area
          max_x: 1000.0 # [m]
          min_x: -1000.0 # [m]
          max_y: 1000.0 # [m]
          min_y: -1000.0 # [m]
