name: Build and test

on:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST
  workflow_dispatch:

env:
  BUILD_DEPEND_FILE: https://raw.githubusercontent.com/tier4/autoware.proj/main/autoware.proj.repos
  SELF_REPO: tier4/autoware_launcher

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pip
        run: |
          apt-get -y update
          apt-get -y install python3-pip

      - name: Install kvaser library
        run: |
          apt-get -y update
          apt-get -y install software-properties-common
          add-apt-repository ppa:astuff/kvaser-linux
          apt-get -y update
          apt-get -y install kvaser-canlib-dev kvaser-drivers-dkms

      - name: Search modified package
        id: list_packages
        run: |
          echo ::set-output name=package_list::$(colcon list --names-only)

      - name: Show target packages
        run: |
          echo "Target packages: ${{ steps.list_packages.outputs.package_list }}"

      - name: Install yq
        run: |
          apt-get -y update
          apt-get -y install wget
          wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.9.1/yq_linux_amd64
          chmod +x /usr/local/bin/yq

      - name: Create build_depends.repos
        run: |
          curl -sSL -H "Authorization: token ${{ secrets.REPO_TOKEN }}" ${{ env.BUILD_DEPEND_FILE }} | sed -e "s|git@github.com:|https://github.com/|g" > build_depends.repos
          repo_key=$(grep ${{ env.SELF_REPO }} build_depends.repos -B2 | grep ":\$" | sed -r 's|\s+([a-zA-Z/]+):|\1|g')
          echo "Remove $repo_key from build_depends.repos"
          yq eval --inplace "del(.repositories.${repo_key})" build_depends.repos

      - name: Set git config for private repositories
        run: |
          git config --local --unset-all http.https://github.com/.extraheader || true
          git config --global url.https://${{ secrets.REPO_TOKEN }}@github.com.insteadof 'https://github.com'

      - name: Clone dependency packages
        run: |
          mkdir dependency_ws
          vcs import dependency_ws < build_depends.repos
          apt-get -y update
          rosdep update
          rosdep install -y --from-paths . --ignore-src --rosdistro foxy

      - name: Build
        run: |
          . /opt/ros/foxy/setup.sh
          colcon build --event-handlers console_cohesion+ \
            --packages-up-to ${{ steps.list_packages.outputs.package_list }} \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: Run tests
        run: |
          . /opt/ros/foxy/setup.sh
          colcon test --event-handlers console_cohesion+ \
            --packages-select ${{ steps.list_packages.outputs.package_list }} \
            --return-code-on-test-failure
