name: Lint Autoware System Design Format

on:
  pull_request:
    paths:
      - "**/*.node.yaml"
      - "**/*.module.yaml"
      - "**/*.system.yaml"
      - "**/*.parameter_set.yaml"
  push:
    branches:
      - main
    paths:
      - "**/*.node.yaml"
      - "**/*.module.yaml"
      - "**/*.system.yaml"
      - "**/*.parameter_set.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint system design format files
        uses: autowarefoundation/autoware_system_designer@main
        with:
          design_files_path: .
